import os
import json
import traceback
import datetime
import argparse
import tiktoken
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from utils.logger import save_agent_result
from utils.color_print import cprint

load_dotenv()

api_key = os.getenv("API_KEY")
base_url = os.getenv("BASE_URL")
model_name = os.getenv("MODEL_NAME")

max_context_window = 128000
max_output_token_nums = 8192

enc = tiktoken.encoding_for_model("gpt-4o")

def build_prompt(pseudocode: str, language: str = "en") -> str:
    """
    Single-round prompt. Directly outputs a function summary string.
    language: "en" (default) or "zh"
    """

    ENGLISH_PROMPT = f"""
You are a program analysis expert specializing in reverse engineering and vulnerability research.
The input is a single pseudocode function generated by a decompiler (e.g., IDA Pro or Ghidra).
The code may contain imprecise types, generic variable names, and compiler artifacts.
Your task is to generate a high-quality function summary that will be used for downstream automated analysis tasks, including:
vulnerability discovery, taint analysis, variable type recovery, and variable name recovery.

[pseudocode begin]
{pseudocode}
[pseudocode end]

Output Requirements:
1. Directly output a high-level semantic description of the function, including:
- The main functionality and purpose of the function
- The roles of important variables and their data flow
- Key control-flow logic
- The functional role/type of the function (e.g., parser / allocator / wrapper / dispatcher / crypto / I/O / utility, etc.)
2. Do NOT output JSON. Output plain text only.
3. Be conservative: if something is unclear, use "unknown" rather than guessing.
4. Focus on usefulness for static analysis.
"""

    CHINESE_PROMPT = f"""
你是一位程序分析专家，专精于逆向工程和漏洞研究。
输入是一个由反编译器（例如 IDA Pro 或 Ghidra）生成的单一伪代码函数。
代码可能包含不精确的类型、通用的变量名以及编译器残留物。
你的任务是生成一个高质量的函数摘要，该摘要将用于下游自动化分析任务，包括：
漏洞发现、污点分析、变量类型恢复和变量名恢复。

======================
伪代码函数
======================
{pseudocode}

======================
输出要求
======================
直接输出对函数功能的高层次语义描述，包括：
1. 函数的主要功能和目的
2. 重要变量的作用及其数据流
3. 关键控制流逻辑
4. 函数的角色类型（如：解析器 / 分配器 / 包装器 / 分发器 / 加密 / 输入输出 / 工具等）

不要输出 JSON 格式。
仅输出纯文本摘要。
保持保守：若信息不明确，请使用“unknown”，不要进行猜测。
关注静态分析的实际可用性。
"""

    if language.lower() == "zh":
        return CHINESE_PROMPT
    return ENGLISH_PROMPT


def run_summary_agent(base_dir: str, pseudocode_file: str, pseudocode: str = None, save_to_file: bool = True):
    """
    Run summary agent

    Args:
        base_dir: Base directory
        pseudocode_file: Pseudocode file name (.c file)
        pseudocode: Pseudocode content (if not provided, will be read from file; if provided, will be used instead)
        save_to_file: Whether to save to file (default True, saved as {funcname}_summary.txt)

    Returns:
        (success: bool, summary: str)
    """
    try:
        pseudocode_path = os.path.join(base_dir, pseudocode_file)
        if pseudocode is None:
            with open(pseudocode_path, "r", encoding="utf-8") as f:
                pseudocode = f.read()

        token_nums = len(enc.encode(pseudocode))
        if token_nums > max_context_window:
            raise RuntimeError(
                f"Pseudocode too large: {token_nums} tokens, summary failed\n{pseudocode_file}"
            )

        llm = ChatOpenAI(
            model=model_name,
            base_url=base_url,
            api_key=api_key,
            temperature=0,
            max_tokens=max_output_token_nums,
            timeout=None,
            max_retries=3,
        )

        # Default prompt language is English
        prompt = build_prompt(pseudocode, language="en")
        cprint(prompt, color="green")

        response = llm.invoke(prompt)
        summary = response.content.strip()
        cprint(summary, color="yellow")

        # Save to individual txt file
        if save_to_file:
            func_name = os.path.splitext(pseudocode_file)[0]
            summary_file = os.path.join(base_dir, f"{func_name}_summary.txt")
            with open(summary_file, "w", encoding="utf-8") as f:
                f.write(summary)

        # Save to log
        save_agent_result(
            base_dir,
            result=summary,
            extra_log=f"Summarized pseudocode file: {pseudocode_file}",
            agent_name="summary"
        )

        return True, summary

    except Exception as e:
        tb_str = traceback.format_exc()
        save_agent_result(base_dir, error=e, tb_str=tb_str, agent_name="summary")
        return False, str(e)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run summary agent on a pseudocode file.")
    parser.add_argument(
        "-d", "--directory",
        type=str,
        default=os.getcwd(),
        help="Base directory"
    )
    parser.add_argument(
        "-f", "--file",
        type=str,
        required=True,
        help="Pseudocode file to summarize"
    )

    args = parser.parse_args()
    base_dir = os.path.abspath(args.directory)

    run_summary_agent(base_dir, args.file)
